version: '3.1'

services:
  backend:
    image: 'danikalmaty/docker-sprint-task'
    container_name: 'self-generated-backend-container'
    depends_on:
      - pgdb
    environment:
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/postgres
      - SPING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - 8004:9999

  pgdb:
    image: postgres
    container_name: 'pg-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 2345:5432